# docker-compose.yml
version: '3'

services:
  django:
    build:
      context: django_uploader
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_STORAGE_BUCKET_NAME: "${AWS_STORAGE_BUCKET_NAME}"
      AWS_S3_ENDPOINT_URL: "${AWS_S3_ENDPOINT_URL}"
      AWS_S3_CUSTOM_DOMAIN: "${AWS_S3_CUSTOM_DOMAIN}"
    ports:
      - "8000:8000"

  nginx:
    build:
      context: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - django

  ftp-uploader:
    build:
      context: ftp_uploader
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      FTP_BUCKET_NAME: "${FTP_BUCKET_NAME}"
      AWS_S3_ENDPOINT_URL: "${AWS_S3_ENDPOINT_URL}"
      AWS_S3_CUSTOM_DOMAIN: "${AWS_S3_CUSTOM_DOMAIN}"
    ports:
      - "21:21"
      - "60000-65535:60000-65535"
    depends_on:
      - minio

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - 9000
      - 9001
    environment:
      MINIO_ROOT_USER: "${AWS_ACCESS_KEY_ID}"
      MINIO_ROOT_PASSWORD: "${AWS_SECRET_ACCESS_KEY}"
    command: server /data --console-address ":9001"
