# docker-compose.yml
version: '3'

services:
  django:
    build:
      context: django_uploader
    ports:
      - "8000:8000"

  nginx:
    build:
      context: nginx_proxy
    ports:
      - "80:80"
      - "81:81"
      - "9000:9000"
    depends_on:
      - django

  ftp-uploader:
    build:
      context: ftp_uploader
    ports:
      - "21:21"
      - "60000-60010:60000-60010"
    depends_on:
      - minio

  minio:
    image: minio/minio
    ports:
#      - "9000:9000"
      - "9001:9001"
    expose:
      - 9000
      - 9001
    environment:
      MINIO_ROOT_USER: 'minio-access-key'
      MINIO_ROOT_PASSWORD: 'minio-secret-key'
    command: server /data --console-address ":9001"
