# docker-compose.yml
version: '3'

services:
  django:
    build:
      context: ./
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_STORAGE_BUCKET_NAME: "${AWS_STORAGE_BUCKET_NAME}"
      AWS_S3_ENDPOINT_URL: "${AWS_S3_ENDPOINT_URL}"
      AWS_S3_CUSTOM_DOMAIN: "${AWS_S3_CUSTOM_DOMAIN}"
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - 9000
      - 9001
    environment:
      MINIO_ROOT_USER: "${AWS_ACCESS_KEY_ID}"
      MINIO_ROOT_PASSWORD: "${AWS_SECRET_ACCESS_KEY}"
    command: server /data --console-address ":9001"
